language: bash
sudo: true
before_script:
  - wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
  - sudo dpkg -i pandoc-1.19.2.1-1-amd64.deb
  - rm pandoc-1.19.2.1-1-amd64.deb
script:
  - make generate-site
after_success:
  - make release
